[package]
name = "alert_sentinel"
version = "0.2.0"
authors = ["st-little"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.6.3", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "6.0.0"
opencv = {version = "0.94.4", features = ["clang-runtime"]}
image = "0.25.6"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.10.3"
tokio = { version = "1.45.1", features = ["rt", "macros", "time"] }
futures = "0.3"
webbrowser = "1.0.4"
dioxus-i18n = "0.4.3"
unic-langid =  "0.9.0"
core_utils = { path = "../core_utils" }

[dependencies.windows-sys]
version = "0.60"
features = [
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
]

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
bundle = []